version: '2'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
#   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  app-1:
    restart: always
    build: ./app/docker-app-1
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
#    command: mvn clean spring-boot:run
    depends_on:
      - nginx
  app-2:
    restart: always
    build: ./app/docker-app-2
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
#    command: mvn clean spring-boot:run
    depends_on:
      - nginx